version: '3.8'

services:
  nginx:
    build:
      context: ./dockerfiles
      dockerfile: nginx.dockerfile
    container_name: nginx_interactive
    ports:
      - 81:80
    volumes:
      - ./:/var/www/html
    depends_on:
      - mysql
      - php
  mysql:
    image: mysql:5.7
    container_name: mysql_interactive
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: interactive
      MYSQL_USER: interactive
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./mysql:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin_interactive
    ports:
      - 8081:80
    environment:
      MYSQL_ROOT_PASSWORD: password
      PMA_HOST: mysql
      PMA_USER: interactive
      PMA_PASSWORD: password
      UPLOAD_LIMIT: 64M
  php:
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
    container_name: php_interactive
    volumes:
      - ./:/var/www/html
  composer:
    build:
      context: ./dockerfiles
      dockerfile: composer.dockerfile
    container_name: composer_interactive
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
  npm:
      image: node:current-alpine
      container_name: npm_interactive
      volumes:
          - ./:/var/www/html
      entrypoint: ["npm"]
      working_dir: /var/www/html
  frontend:
      build:
          context: ./frontend
          dockerfile: Dockerfile
      container_name: frontend_interactive
      ports:
          - "5173:5173"
      volumes:
          - ./frontend:/app
          - ./app/node_modules
      command: ["npm", "run", "dev"]
  artisan:
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
    container_name: artisan_interactive
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - mysql
    entrypoint: ["php", "/var/www/html/artisan"]
